version: "3"
services:
  app:
    image: husseinawala/micro-service-documentation:latest
    command: yarn run ${ENV:-dev}
    volumes:
      - /app/node_modules
    networks:
      - app
    logging:
      driver: ${LOGGING_DRIVER:-json-file}
    restart: always

networks:
  app:
    driver: bridge
